### ISSUE TITLE
Documentation for production enviornment

### ISSUE THREAD

**Issue by sualko** [Public-Health-Informatics-Munich/covid19-teststation-termine#24]
Hi everyone,

thanks for this great application. It's awesome that you put this as open source licensed project on Github.

I need to set this up for a small test station and want to know if there are any documentation for production use. Currently I would run it as docker, but I'm wondering why it's labeled as test setup.

Also some basic dev instructions would be nice. For example what is the `termine-bo`? 

Best regards,
Klaus

**Comment by sualko** [comment]
Please also add a description for this application, because I guess it's not intended for self registration with some kind of email verification.

**Comment by vschaeidt** [comment]
Hi, first of, thank you for the feedback!

What would help you to use this in production? The current setup where this is used is running in a k8s cluster, but we've had it running on AWS too.
Running it by starting the docker containers manually would also work, but then you'd probably have to spend some time thinking about DB backups.

The `termine-bo` is just the administration interface, I guess we could improve that wording.

Concerning the self registration, that was indeed not an use-case we had, as usually you'd have less time-slots than people wanting to get tested, requiring some sort of filter.
We did however experiment with an "anonymous mode", where anybody could register appointments (by setting the `DISABLE_AUTH=True` in the environment), and from there on I could imagine that a registration process could be imaginable.

what exactly would be your use-case, and what would you need to be enabled to use this project?

Cheers,
Valentin

**Comment by sualko** [comment]
Sorry for my late response, but I had to write our own booking system in some kind of a hurry. If you are interested, you can find it here: https://github.com/drkTettnang/corona-testing.

> What would help you to use this in production?

Maybe I miss some knowledge about python or so, but from the readme it was not clear to me, how this should be running in production.
